# Generated by Django 2.2.17 on 2022-01-18 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parasite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, default='default/default.jpg', upload_to='parasite_images')),
            ],
            options={
                'verbose_name_plural': 'Parasites',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='default/default.jpg', upload_to='profile_images')),
                ('role', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='default/default.jpg', upload_to='user/%Y/%m/%d/')),
                ('text', models.TextField(max_length=300)),
                ('file', models.FileField(blank=True, upload_to='user/%Y/%m/%d/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField()),
                ('parasite', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='parasites_app.Parasite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parasites_app.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to='parasites_app.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='parasites_app.UserProfile')),
            ],
        ),
    ]
