# Generated by Django 3.1.5 on 2022-03-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parasites_app', '0002_auto_20220316_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
