# Generated by Django 2.2.17 on 2022-03-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parasites_app', '0006_auto_20220317_1511'),
        ('parasites_app', '0005_auto_20220317_1052'),
    ]

    operations = [
    ]
