# Generated by Django 2.2.17 on 2022-03-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parasites_app', '0007_auto_20220317_1648'),
        ('parasites_app', '0007_merge_20220317_1606'),
    ]

    operations = [
    ]
