# Generated by Django 3.2.9 on 2022-03-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parasites_app', '0008_auto_20220317_2318'),
        ('parasites_app', '0008_merge_20220317_2032'),
    ]

    operations = [
    ]
